Thu Sep  8 17:38:15 2022 - INFO  - Start to prepare the test environment.
spawn ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa): 
Created directory '/root/.ssh'.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /root/.ssh/id_rsa
Your public key has been saved in /root/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:2jDfqb0Ra0nJY66vMCH7Anbfb58EGptFmGfdqdv2UCk root@openEuler-riscv64
The key's randomart image is:
+---[RSA 3072]----+
|                 |
|         o . . . |
|        o + . o  |
|         = . .  .|
|    . + S X .E ..|
|  o .o B @ B o.. |
| . o..+.* O o +  |
|    ...o.=.o o o |
|     .. +==oo   .|
+----[SHA256]-----+
spawn ssh-copy-id root@
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/root/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: ERROR: ssh: Could not resolve hostname : Name or service not known

send: spawn id exp3 not open
    while executing
"send "yes\n""
Thu Sep  8 17:40:51 2022 - INFO  - End to prepare the test environment.
Thu Sep  8 17:40:52 2022 - INFO  - Start to run test.
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
Thu Sep  8 17:41:12 2022 - ERROR - Check ansible --help failed.
Thu Sep  8 17:41:12 2022 - ERROR - oe_test_ansible_01.sh line 30
Thu Sep  8 17:55:19 2022 - INFO  - End to run test.
Thu Sep  8 17:55:19 2022 - ERROR - failed to execute the case.
Thu Sep  8 17:55:20 2022 - INFO  - Start to restore the test environment.
Thu Sep  8 17:56:07 2022 - INFO  - End to restore the test environment.
