Fri Sep  9 06:37:40 2022 - INFO  - Start to prepare the database config.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 168, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Fri Sep  9 06:38:40 2022 - WARN  - the remote password uses the default configuration.
Fri Sep  9 06:38:41 2022 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r ./common/test-vm.secrets @:/etc/ipsec.d
ssh: Could not resolve hostname : Name or service not known
lost connection
Fri Sep  9 06:38:42 2022 - ERROR - Failed in remote SCP operation: 1
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 06:38:43 2022 - ERROR - Failed in remote CMD operation:1
Redirecting to: systemctl restart ipsec.service
Job for ipsec.service failed because the control process exited with error code.
See "systemctl status ipsec.service" and "journalctl -xeu ipsec.service" for details.
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 06:38:48 2022 - ERROR - Failed in remote CMD operation:1
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:38:50 2022 - INFO  - End to prepare the database config.
Fri Sep  9 06:38:51 2022 - INFO  - Start to run test.
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:38:52 2022 - ERROR - Check ipsec auto --listpubkeys failed.
Fri Sep  9 06:38:53 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 34
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:38:54 2022 - ERROR - Check ipsec auto --listcerts failed.
Fri Sep  9 06:38:55 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 36
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:38:56 2022 - ERROR - Check ipsec auto --checkpubkeys failed.
Fri Sep  9 06:38:57 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 38
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:38:58 2022 - ERROR - Check ipsec auto --listcacerts failed.
Fri Sep  9 06:38:59 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 40
ipsec auto: unknown option "--listgroups"
Fri Sep  9 06:39:00 2022 - ERROR - Check ipsec auto --showonly --utc --listgroups failed.
Fri Sep  9 06:39:00 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 42
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:39:01 2022 - ERROR - Check ipsec auto --listcrls failed.
Fri Sep  9 06:39:02 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 44
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:39:03 2022 - ERROR - Check ipsec auto --listall failed.
Fri Sep  9 06:39:04 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 46
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:39:06 2022 - ERROR - Check ipsec auto --purgeocsp failed.
Fri Sep  9 06:39:07 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 48
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:39:08 2022 - ERROR - Check ipsec auto --rereadsecrets failed.
Fri Sep  9 06:39:08 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 50
ipsec auto: unknown option "--rereadgroups"
Fri Sep  9 06:39:09 2022 - ERROR - Check ipsec auto --rereadgroups failed.
Fri Sep  9 06:39:10 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 52
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:39:11 2022 - ERROR - Check ipsec crls failed.
Fri Sep  9 06:39:12 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 55
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:39:13 2022 - ERROR - Check ipsec auto --rereadcerts failed.
Fri Sep  9 06:39:14 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 57
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
Fri Sep  9 06:39:15 2022 - ERROR - Check ipsec auto --rereadall failed.
Fri Sep  9 06:39:16 2022 - ERROR - oe_test_libreswan_ipsec_auto_2.sh line 59
Fri Sep  9 06:39:16 2022 - INFO  - End to run test.
Fri Sep  9 06:39:17 2022 - ERROR - failed to execute the case.
Fri Sep  9 06:39:18 2022 - INFO  - Start to restore the test environment.
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 06:39:19 2022 - ERROR - Failed in remote CMD operation:1
Fri Sep  9 06:39:42 2022 - INFO  - End to restore the test environment.
