Fri Sep  9 02:59:49 2022 - INFO  - Start to prepare the test environment.
Failed to start etcd.service: Unit etcd.service not found.
Fri Sep  9 03:00:24 2022 - INFO  - End to prepare the test environment.
Fri Sep  9 03:00:25 2022 - INFO  - Start to run test.
Unit etcd.service could not be found.
Fri Sep  9 03:00:26 2022 - ERROR - Check etcd.service start failed
Fri Sep  9 03:00:27 2022 - ERROR - oe_test_etcd_05.sh line 29
oe_test_etcd_05.sh: line 30: etcdctl: command not found
Fri Sep  9 03:00:27 2022 - ERROR - Check etcdctl defrag failed.
Fri Sep  9 03:00:28 2022 - ERROR - oe_test_etcd_05.sh line 31
oe_test_etcd_05.sh: line 32: etcdctl: command not found
Fri Sep  9 03:00:29 2022 - ERROR - Check etcdctl --endpoints failed.
Fri Sep  9 03:00:30 2022 - ERROR - oe_test_etcd_05.sh line 33
oe_test_etcd_05.sh: line 34: etcdctl: command not found
Fri Sep  9 03:00:30 2022 - ERROR - Check etcdctl alarm disarm failed.
Fri Sep  9 03:00:31 2022 - ERROR - oe_test_etcd_05.sh line 35
oe_test_etcd_05.sh: line 36: etcdctl: command not found
Fri Sep  9 03:00:32 2022 - ERROR - Check etcdctl alarm listfailed.
Fri Sep  9 03:00:32 2022 - ERROR - oe_test_etcd_05.sh line 37
oe_test_etcd_05.sh: line 38: etcdctl: command not found
Fri Sep  9 03:00:33 2022 - ERROR - Check etcdctl check datascale failed.
Fri Sep  9 03:00:34 2022 - ERROR - oe_test_etcd_05.sh line 39
oe_test_etcd_05.sh: line 40: etcdctl: command not found
Fri Sep  9 03:00:34 2022 - ERROR - Check etcdctl check perf failed.
Fri Sep  9 03:00:35 2022 - ERROR - oe_test_etcd_05.sh line 41
Fri Sep  9 03:00:36 2022 - INFO  - End to run test.
Fri Sep  9 03:00:36 2022 - ERROR - failed to execute the case.
Fri Sep  9 03:00:37 2022 - INFO  - Start to restore the test environment.
Failed to stop etcd.service: Unit etcd.service not loaded.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Last metadata expiration check: 0:05:54 ago on Fri 09 Sep 2022 02:54:29 AM CST.\nNo match for argument: etcd\nError: Unable to find a match: etcd'
Fri Sep  9 03:00:40 2022 - INFO  - End to restore the test environment.
