Fri Sep  9 07:49:09 2022 - INFO  - Start to prepare the test environment.
Fri Sep  9 07:49:48 2022 - ERROR - You need to check the environment configuration file to see if this node information exists.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 168, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Fri Sep  9 07:49:53 2022 - ERROR - You need to check the environment configuration file to see if this node information exists.
Fri Sep  9 07:49:54 2022 - INFO  - End to prepare the test environment.
Fri Sep  9 07:49:54 2022 - INFO  - Start to run test.
Try “rdisc6 -h” for more information.
Try “rdisc6 -h” for more information.
Fri Sep  9 07:49:55 2022 - ERROR - oe_test_ndisc6_rdisc6.sh line 31
Try “rdisc6 -h” for more information.
Fri Sep  9 07:49:56 2022 - ERROR - oe_test_ndisc6_rdisc6.sh line 35
ndisc6: IPv6 Neighbor/Router Discovery userland tool 1.0.4 ($Rev$)
Usage: rdisc6 [options] [IPv6 address] <interface>
Fri Sep  9 07:49:58 2022 - INFO  - End to run test.
Fri Sep  9 07:49:58 2022 - ERROR - failed to execute the case.
Fri Sep  9 07:49:59 2022 - INFO  - Start to restore the test environment.
Fri Sep  9 07:50:14 2022 - INFO  - End to restore the test environment.
